### ISSUE TITLE
Choosing to change the resolution to 1200px by 800px results in an error

### ISSUE THREAD

**Issue by JonBetts** [nckstwrt/CM0102Loader#1]
This isn't too technical, but basically I'm assuming that the RGN files aren't converted in the background like they are when using the CM0102Patcher, which obviously causes an issue when trying to change the resolution to 1200 x 800. Error message below.

![Capture](https://user-images.githubusercontent.com/1726558/103838919-30d46e00-5086-11eb-880d-5d28fbd2a0c9.PNG)

On a side note, is this frequently updated alongside the Patcher, so that all the newer options can be changed? It's really useful having the Loader, knowing that it doesn't actually permanently modify the CM executable file :smile:

**Comment by JonBetts** [comment]
Nick mentioned that changing the resolution obviously edits the existing data files, which renders the usage of the Loader above the Patcher pointless. I agree, so will close this issue.

**Comment by nckstwrt** [comment]
I'm going to embed those files in the exe and then make it so change background is turned off. Then it will work without impact :)
